repos:
  - repo: https://github.com/adamchainz/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        args: ["--line-length", "120"]
        files: \.rst$
        additional_dependencies:
        - black==22.12.0

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args: ["--prose-wrap", "always"]
        files: \.rst$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        files: \.rst$
        args:
          - "--ignore-words-list=ist"

  # - repo: https://github.com/PyCQA/doc8
  #   rev: v1.1.2
  #   hooks:
  #     - id: doc8
  #       args: ["--max-line-length", "120"]
  #       files: \.rst$

  # - repo: https://github.com/myint/rstcheck
  #   rev: v6.2.4
  #   hooks:
  #     - id: rstcheck
  #       files: \.rst$
